-- Insert sample therapy types into the therapies table

INSERT INTO therapies (id, title, short_description, icon, detailed_info, when_needed, is_active) VALUES
('cognitive-behavioral-therapy',
 'Cognitive Behavioral Therapy (CBT)',
 'A structured, goal-oriented therapy that helps identify and change negative thought patterns and behaviors.',
 'BRAIN',
 'Cognitive Behavioral Therapy (CBT) is one of the most researched and effective forms of psychotherapy. It focuses on identifying and challenging negative thought patterns and behaviors that contribute to emotional distress. CBT is based on the principle that our thoughts, feelings, and behaviors are interconnected. By changing negative thinking patterns, we can improve our emotional well-being and behavior. Sessions typically involve homework assignments, thought records, and practical exercises to practice new coping skills.',
 'CBT is effective for treating depression, anxiety disorders, panic attacks, phobias, PTSD, obsessive-compulsive disorder, eating disorders, and substance abuse. It is particularly helpful when you want to develop practical coping strategies and see measurable progress in a structured timeframe.',
 true),

('psychodynamic-therapy',
 'Psychodynamic Therapy',
 'Explores unconscious thoughts and past experiences to understand current behavior patterns.',
 'SEARCH',
 'Psychodynamic therapy is based on the idea that unconscious thoughts and past experiences significantly influence our current behavior and relationships. This approach helps clients gain insight into recurring patterns in their lives, often stemming from childhood experiences or past relationships. The therapeutic relationship itself becomes a tool for understanding and healing. Sessions focus on exploring emotions, dreams, and free associations to uncover underlying motivations and conflicts.',
 'This therapy is beneficial for those dealing with relationship issues, recurring life patterns, depression, anxiety, personality disorders, and those seeking deep self-understanding. It is ideal when you want to explore the root causes of your problems rather than just addressing symptoms.',
 true),

('humanistic-therapy',
 'Humanistic/Person-Centered Therapy',
 'Emphasizes personal growth, self-acceptance, and the inherent capacity for positive change.',
 'GROWTH',
 'Humanistic therapy, particularly Carl Rogers person-centered approach, emphasizes the inherent goodness and potential for growth in every individual. The therapist provides unconditional positive regard, empathy, and genuine acceptance, creating a safe space for self-exploration. This approach believes that clients are the experts on their own lives and have the capacity to find their own solutions when provided with the right supportive environment.',
 'Ideal for individuals seeking personal growth, struggling with self-esteem issues, identity concerns, life transitions, creative blocks, or those who want to develop greater self-awareness and authenticity. It is particularly effective for highly sensitive people and those who have felt judged or misunderstood.',
 true),

('family-therapy',
 'Family Therapy',
 'Addresses relationship dynamics and communication patterns within family systems.',
 'FAMILY',
 'Family therapy views problems within the context of the family system rather than focusing solely on the individual. It examines communication patterns, roles, boundaries, and dynamics that may be contributing to difficulties. The goal is to improve family functioning, enhance communication skills, and help family members understand each other better. Sessions may include the entire family or various combinations of family members.',
 'Recommended for families dealing with communication problems, behavioral issues with children or teenagers, divorce or separation, blended family challenges, substance abuse affecting the family, grief and loss, chronic illness, or major life transitions. It is also helpful for couples considering marriage or those experiencing relationship difficulties.',
 true),

('dialectical-behavior-therapy',
 'Dialectical Behavior Therapy (DBT)',
 'Teaches skills for managing intense emotions, improving relationships, and tolerating distress.',
 'BALANCE',
 'DBT was originally developed for individuals with borderline personality disorder but has proven effective for various mental health conditions involving emotional dysregulation. It combines cognitive-behavioral techniques with mindfulness practices and distress tolerance skills. DBT teaches four core modules: mindfulness, distress tolerance, emotion regulation, and interpersonal effectiveness. The therapy emphasizes the concept of wise mind - balancing emotional and rational thinking.',
 'Particularly effective for individuals with borderline personality disorder, self-harm behaviors, suicidal ideation, eating disorders, substance abuse, PTSD, chronic feelings of emptiness, intense and unstable relationships, or difficulty managing strong emotions. It is ideal for those who struggle with black-and-white thinking and emotional extremes.',
 true),

('acceptance-commitment-therapy',
 'Acceptance and Commitment Therapy (ACT)',
 'Focuses on accepting difficult thoughts and feelings while committing to value-based actions.',
 'TARGET',
 'ACT is based on the premise that suffering is a normal part of the human experience, and that trying to eliminate or control painful thoughts and feelings often increases suffering. Instead, ACT teaches psychological flexibility - the ability to stay present with difficult experiences while taking action guided by personal values. The therapy uses mindfulness, acceptance, and commitment strategies to help clients live more fulfilling lives.',
 'Effective for chronic pain, anxiety disorders, depression, substance abuse, workplace stress, chronic illness, and life transitions. It is particularly helpful for perfectionists, people who struggle with control issues, those dealing with chronic conditions, or anyone who wants to live more authentically according to their values.',
 true),

('emdr-therapy',
 'Eye Movement Desensitization and Reprocessing (EMDR)',
 'Uses bilateral stimulation to help process and heal from traumatic memories and experiences.',
 'EYE',
 'EMDR is an evidence-based psychotherapy for PTSD and trauma. It helps the brain process traumatic memories that have become stuck and continue to cause distress. During EMDR sessions, clients recall traumatic events while engaging in bilateral stimulation (typically eye movements), which helps the brain process the memories in a healthier way. The goal is to reduce the emotional charge associated with traumatic memories.',
 'Primarily used for PTSD, trauma, phobias, panic attacks, anxiety disorders, depression related to trauma, grief and loss, disturbing memories, and performance anxiety. It is particularly effective for single-incident traumas like accidents, assaults, or natural disasters, as well as complex trauma from childhood abuse or neglect.',
 true),

('gestalt-therapy',
 'Gestalt Therapy',
 'Emphasizes present-moment awareness and personal responsibility for thoughts, feelings, and actions.',
 'MASK',
 'Gestalt therapy focuses on the here-and-now experience, helping clients become more aware of their thoughts, feelings, and behaviors in the present moment. It emphasizes personal responsibility and the client ability to make healthy choices. Techniques may include the empty chair exercise, dream work, and body awareness exercises. The therapy helps integrate different aspects of the self to achieve wholeness (gestalt means whole in German).',
 'Beneficial for individuals seeking greater self-awareness, those struggling with unfinished business from the past, relationship issues, depression, anxiety, grief, creative blocks, and personal growth. It is particularly effective for people who intellectualize their problems and need to reconnect with their emotions and body awareness.',
 true),

('narrative-therapy',
 'Narrative Therapy',
 'Helps people re-author their life stories and separate their identity from their problems.',
 'BOOK',
 'Narrative therapy views people as the authors of their own lives and helps them examine and re-write the stories they tell about themselves. It distinguishes between the person and their problems, helping clients identify unique outcomes and preferred stories about their lives. This approach recognizes that problems are often maintained by dominant cultural narratives and helps people develop more empowering personal narratives.',
 'Particularly effective for individuals dealing with identity issues, depression, anxiety, trauma, grief, addiction recovery, eating disorders, and relationship problems. It is especially helpful for marginalized communities, adolescents, and anyone who feels defined by their problems rather than their strengths and values.',
 true),

('somatic-therapy',
 'Somatic Therapy',
 'Addresses trauma and stress stored in the body through body-awareness and movement techniques.',
 'BODY',
 'Somatic therapy recognizes that trauma and stress are stored not just in the mind but also in the body. It uses body-based techniques to help release tension, trauma, and chronic stress patterns. Approaches may include breathing exercises, movement, touch (when appropriate), and developing body awareness. The therapy helps clients develop a healthier relationship with their bodies and learn to recognize and respond to body signals.',
 'Effective for trauma, PTSD, chronic pain, anxiety, depression, chronic fatigue, eating disorders, and stress-related physical symptoms. It is particularly beneficial for individuals who have experienced physical or sexual trauma, those with chronic health conditions, or people who feel disconnected from their bodies.',
 true),

('solution-focused-therapy',
 'Solution-Focused Brief Therapy (SFBT)',
 'Concentrates on solutions and strengths rather than problems, typically short-term and goal-oriented.',
 'BULB',
 'SFBT is a goal-oriented therapeutic approach that focuses on solutions rather than problems. It helps clients identify their strengths, resources, and past successes to create positive change. The therapy is typically brief, lasting 6-12 sessions, and uses techniques like the miracle question and scaling questions to help clients envision and work toward their preferred future. It assumes that clients already have the skills and resources needed to create change.',
 'Ideal for individuals who want short-term, focused therapy for specific goals, relationship issues, work stress, mild to moderate depression and anxiety, behavioral changes, and life transitions. It is particularly effective for motivated clients who prefer a positive, forward-looking approach rather than extensive exploration of past issues.',
 true),

('mindfulness-based-therapy',
 'Mindfulness-Based Therapy',
 'Incorporates meditation and mindfulness practices to develop present-moment awareness and emotional regulation.',
 'LOTUS',
 'Mindfulness-based therapies integrate meditation and mindfulness practices with traditional therapeutic approaches. These therapies help develop present-moment awareness, emotional regulation, and a non-judgmental relationship with thoughts and feelings. Common approaches include Mindfulness-Based Stress Reduction (MBSR), Mindfulness-Based Cognitive Therapy (MBCT), and various forms of meditation-informed psychotherapy.',
 'Beneficial for stress reduction, anxiety, depression (particularly preventing relapse), chronic pain, chronic illness, eating disorders, addiction recovery, and general wellness. It is ideal for those interested in developing a meditation practice, people dealing with rumination or worry, and individuals seeking a holistic approach to mental health.',
 true);