name: Test Deployment

on:
  workflow_dispatch:

jobs:
  test:
    name: Test Connection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}

      - name: Test connection
        run: |
          echo "Testing Digital Ocean connection..."
          doctl compute droplet list --context thappy || doctl compute droplet list
          echo "Connection test completed"